################################################################################
#
# EASYRPG_PLAYER
#
################################################################################
# Version.: Release on Oct 3, 2020
EASYRPG_PLAYER_VERSION = 0.6.2.3
EASYRPG_PLAYER_DEPENDENCIES = sdl2 zlib fmt libpng freetype mpg123 libvorbis opusfile sdl2_mixer liblcf pixman speexdsp libxmp wildmidi
EASYRPG_PLAYER_LICENSE = MIT
EASYRPG_PLAYER_SITE = $(call github,EasyRPG,Player,$(EASYRPG_PLAYER_VERSION))

EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
EASYRPG_PLAYER_CONF_OPTS += -DPLAYER_BUILD_EXECUTABLE=ON
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
EASYRPG_PLAYER_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"

EASYRPG_PLAYER_CONF_ENV += LDFLAGS=-lpthread

# Should be set when the package cannot be built inside the source tree but needs a separate build directory.
EASYRPG_PLAYER_SUPPORTS_IN_SOURCE_BUILD = NO

define EASYRPG_PLAYER_EVMAPY
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/easyrpg/easyrpg-player/easyrpg.easyrpg.keys $(TARGET_DIR)/usr/share/evmapy
endef

EASYRPG_PLAYER_POST_INSTALL_TARGET_HOOKS += EASYRPG_PLAYER_EVMAPY


$(eval $(cmake-package))
